-- ============================================================================
-- Margin Guide — schema.
-- ----------------------------------------------------------------------------
-- Replaces the VBA workbook "Buyer Margin Guide v1.0.xlsm" (3 sheets:
-- MarginGuide UI, MarginBreakdown lookup, HelpLanguage). The buyer picks a
-- category, device and condition, types the resale projection, and gets three
-- percentages plus the coaching language for that item.
--
-- THE THREE PERCENTAGES ARE SHARE-OF-PROJECTION PAID, NOT MARGIN RETAINED.
-- They ascend as the offer gets more generous: start_pct is the opening offer
-- (best for the store), team_pct is as high as a team member may go alone, and
-- mgr_pct is the manager's ceiling before the DM is involved. The workbook
-- called these columns "Lowest Margin / Highest Margin / MANAGER HIGHEST",
-- which reads backwards to a new buyer; the names here follow what the numbers
-- actually do.
--
-- THE KEY STRUCTURAL FINDING: the workbook's 364 (band x condition) rows only
-- ever use 10 distinct percentage triples. So the triples live once in
-- mg_tiers and mg_band_conditions points at them. Retuning company policy is
-- one row, not 63 — and a tier cannot be half-updated into an inconsistent
-- state, which the flat sheet allowed.
--
-- Price bands are numeric (price_min / price_max), not the workbook's free-text
-- "Model" strings. That kills a whole typo class ("Bewteen", "Less Then",
-- Motherboard's bands mislabeled "Storage ...") and makes band selection
-- computable: the buyer types a projection and the band resolves itself.
--
-- Video Games below $20 is not a percentage at all — the workbook's reminders
-- carry flat per-game pay rules. mg_bands.pay_mode = 'flat' covers that, with
-- flat_low / flat_high in dollars instead of a tier.
--
-- No RLS policies, matching every other table in this project: closed to the
-- anon client, all access through the service-role `margin-guide` edge fn.
--
-- Seed data lands in 0006_margin_guide_seed.sql.
-- Apply via Supabase MCP `apply_migration` (or the SQL editor).
-- ============================================================================

-- 1. The 10 percentage triples. Editing one retunes every band using it.
--    The check constraint enforces the ladder's shape, so a bad edit is
--    rejected at the database rather than silently shipping to buyers.
create table public.mg_tiers (
  id          smallint primary key,
  slug        text     not null unique,
  name        text     not null,
  start_pct   numeric  not null,   -- opening offer: fair to the customer, store wins
  team_pct    numeric  not null,   -- highest a team member may go unaided
  mgr_pct     numeric  not null,   -- manager ceiling; above this, get the DM
  sort_order  smallint not null default 0,
  updated_by  text,
  updated_at  timestamptz not null default now(),
  constraint mg_tiers_ladder check (
    start_pct > 0 and start_pct < team_pct and team_pct < mgr_pct and mgr_pct <= 100
  )
);

-- 2. Condition grades. A lookup rather than a hardcoded frontend array so the
--    display order and the plain-English meaning are editable — CHECKOUT in
--    particular needed explaining (it is the Checkout pricing program, not a
--    damage grade).
create table public.mg_conditions (
  name        text     primary key,
  blurb       text,
  sort_order  smallint not null default 0
);

-- 3. Category + device. help_key joins to the language tables; several devices
--    deliberately share one key (the four Audio/Home Theatre devices all point
--    at 'Audio/Home Theatre', the three Miscellaneous sizes at
--    'Miscellaneous'), which is how the workbook's HelpLanguage sheet was
--    already organized.
create table public.mg_devices (
  id          smallint generated by default as identity primary key,
  category    text     not null,
  device      text     not null,
  help_key    text     not null,
  sort_order  smallint not null default 0,
  active      boolean  not null default true,
  unique (category, device)
);
create index mg_devices_help_key_idx on public.mg_devices (help_key);

-- 4. Numeric price bands. price_max null means "and up". A band with no price
--    split at all (Portable Speakers, Any Retro Console) is stored as
--    0 .. null, so the resolver always finds exactly one match.
create table public.mg_bands (
  id          integer  generated by default as identity primary key,
  device_id   smallint not null references public.mg_devices(id) on delete cascade,
  label       text     not null,
  price_min   numeric  not null default 0,
  price_max   numeric,
  pay_mode    text     not null default 'percent',
  flat_low    numeric,           -- pay_mode='flat': dollars per item, low end
  flat_high   numeric,           -- ...and high end
  sort_order  smallint not null default 0,
  constraint mg_bands_pay_mode  check (pay_mode in ('percent', 'flat')),
  constraint mg_bands_range     check (price_max is null or price_max > price_min),
  constraint mg_bands_flat_pair check (
    pay_mode <> 'flat' or (flat_low is not null and flat_high is not null and flat_high >= flat_low)
  )
);
create index mg_bands_device_idx on public.mg_bands (device_id, sort_order);

-- 5. The assignment grid: which tier applies to this band in this condition.
--    A missing row is meaningful, not an oversight — the workbook has no
--    Broken row for accessories or headphones because we do not buy those, and
--    the reminders say so out loud ("DO NOT BUY ANY BROKEN ACCESSORIES...").
--    The tool renders an absent condition as struck-through rather than
--    quietly dropping it from the picker.
create table public.mg_band_conditions (
  band_id    integer  not null references public.mg_bands(id) on delete cascade,
  condition  text     not null references public.mg_conditions(name),
  tier_id    smallint not null references public.mg_tiers(id),
  primary key (band_id, condition)
);
create index mg_band_conditions_tier_idx on public.mg_band_conditions (tier_id);

-- 6. Reminders, condition help and testing tips.
--    is_gate marks a hard precondition on the purchase rather than advice —
--    "MOTHERBOARDS MUST BE TESTED IN ORDER TO BE PURCHASED", "no MDM on the
--    device", "have the customer fly the drone", "get it cleared with the
--    manager". Those were buried as bullets among tips in the workbook, where
--    they read as suggestions. The tool lifts them above the ladder and leaves
--    them out of the list below, so each rule appears exactly once.
--    is_must is softer: still a rule, stays in its list, rendered emphasized.
create table public.mg_help_items (
  id          integer  generated by default as identity primary key,
  help_key    text     not null,
  kind        text     not null,
  body        text     not null,
  is_gate     boolean  not null default false,
  is_must     boolean  not null default false,
  sort_order  smallint not null default 0,
  constraint mg_help_kind check (kind in ('reminder', 'condition', 'testing'))
);
create index mg_help_items_key_idx on public.mg_help_items (help_key, kind, sort_order);

-- 7. Rebuttals. `say` is the line a buyer can read almost verbatim to the
--    customer; `why` is the business reason behind it, for when they get
--    pushed. `conditions` empty means the rebuttal always applies; otherwise
--    it only surfaces for the grades listed, so a Mint iPhone does not show
--    the micro-scratches line.
--    `say` is nullable on purpose: the workbook's text is buyer-facing notes,
--    not spoken lines. Rows seeded from it carry `why` only until the voice
--    pass is done, and the tool falls back to `why` when `say` is null.
create table public.mg_rebuttals (
  id          integer  generated by default as identity primary key,
  help_key    text     not null,
  name        text     not null,
  say         text,
  why         text     not null,
  conditions  text[]   not null default '{}',
  sort_order  smallint not null default 0
);
create index mg_rebuttals_key_idx on public.mg_rebuttals (help_key, sort_order);

-- 8. Resolver: projection dollars -> the one matching band for a device.
--    Lower bound inclusive, upper bound exclusive, so adjacent bands never
--    both match and a projection exactly on a boundary lands in the higher
--    band ($350 on an iPhone is the $350+ band, not $150-$350).
create or replace function public.mg_resolve_band(p_device_id smallint, p_projection numeric)
returns integer
language sql
stable
as $$
  select b.id
    from public.mg_bands b
   where b.device_id = p_device_id
     and p_projection >= b.price_min
     and (b.price_max is null or p_projection < b.price_max)
   order by b.price_min desc
   limit 1;
$$;

-- 9. RLS on, no policies — the pattern every other table in this project uses.
--    The anon key ships in speeks.js, so without this an employee (or anyone
--    who views source) could rewrite the company's buy ladder. Service role
--    bypasses RLS, so the `margin-guide` edge fn is unaffected.
alter table public.mg_tiers           enable row level security;
alter table public.mg_conditions      enable row level security;
alter table public.mg_devices         enable row level security;
alter table public.mg_bands           enable row level security;
alter table public.mg_band_conditions enable row level security;
alter table public.mg_help_items      enable row level security;
alter table public.mg_rebuttals       enable row level security;

comment on table  public.mg_tiers            is 'The 10 percentage triples every band row shares. Share of projection PAID, ascending.';
comment on table  public.mg_band_conditions  is 'band x condition -> tier. A missing row means we do not buy that condition in that band.';
comment on column public.mg_bands.pay_mode   is 'percent = use the tier ladder; flat = pay flat_low..flat_high dollars per item (Video Games under $20).';
comment on column public.mg_help_items.is_gate is 'Hard precondition on the purchase. Rendered above the ladder, omitted from the list below.';
comment on column public.mg_rebuttals.say    is 'Line to say to the customer. Null until the voice pass reaches this row; tool falls back to why.';
